# secret : 사실한 민감한 정보 전용의 ConfigMap
# 비밀번호, API 키, 인증서처럼 민감한 정보값을 Pod 밖에서 안전하게 관리하기 위한 객체

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque                 # 일반적인 Secret 타입
data:
  # base64 인코딩된 값
  username: YWRtaW4=           # StringData로 admin
  password: c2VjcmV0cGFzczEyMw==  # StringData로 secretpass123

#stringData로 작성하면 자동으로 base64 인코딩되어 저장
#더 편리하지만, YAML 파일에 평문이 남는 건 주의해야 하기에 base64 인코딩된 값으로 작성