apiVersion: apps/v1        # Pod는 v1, Deployment는 apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2              # ⭐ Pod를 n개 유지. 값 수정 후 적용 가능(예: 5->2)
  selector:                # ⭐ 관리할 Pod를 찾는 조건
    matchLabels:
      app: nginx
  template:                # ⭐ Pod 템플릿 (Pod 정의와 동일)
    metadata:
      labels:
        app: nginx         # selector와 일치해야 함!
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
## 롤링 업데이트 동작
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 1        # 동시에 추가로 만들 수 있는 Pod 수
#      maxUnavailable: 0  # 동시에 중단될 수 있는 Pod 수