apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: app
      image: nginx:1.25
      envFrom:               # ⭐ ConfigMap 전체를 환경변수로
        - configMapRef:
            name: app-config   # ConfigMap 이름